//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EKirtasiye.N11.ProductSellingService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProductSellingServicePortSoap11", Namespace="http://www.n11.com/ws/schemas")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductSkuBasicRequest))]
    public partial class ProductSellingServicePortService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback StopSellingProductByProductIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback StopSellingProductBySellerCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartSellingProductByProductIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartSellingProductBySellerCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProductSellingServicePortService() {
            this.Url = global::EKirtasiye.N11.Properties.Settings.Default.EKirtasiye_N11_ProductSellingService_ProductSellingServicePortService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event StopSellingProductByProductIdCompletedEventHandler StopSellingProductByProductIdCompleted;
        
        /// <remarks/>
        public event StopSellingProductBySellerCodeCompletedEventHandler StopSellingProductBySellerCodeCompleted;
        
        /// <remarks/>
        public event StartSellingProductByProductIdCompletedEventHandler StartSellingProductByProductIdCompleted;
        
        /// <remarks/>
        public event StartSellingProductBySellerCodeCompletedEventHandler StartSellingProductBySellerCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("StopSellingProductByProductIdResponse", Namespace="http://www.n11.com/ws/schemas")]
        public StopSellingProductByProductIdResponse StopSellingProductByProductId([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.n11.com/ws/schemas")] StopSellingProductByProductIdRequest StopSellingProductByProductIdRequest) {
            object[] results = this.Invoke("StopSellingProductByProductId", new object[] {
                        StopSellingProductByProductIdRequest});
            return ((StopSellingProductByProductIdResponse)(results[0]));
        }
        
        /// <remarks/>
        public void StopSellingProductByProductIdAsync(StopSellingProductByProductIdRequest StopSellingProductByProductIdRequest) {
            this.StopSellingProductByProductIdAsync(StopSellingProductByProductIdRequest, null);
        }
        
        /// <remarks/>
        public void StopSellingProductByProductIdAsync(StopSellingProductByProductIdRequest StopSellingProductByProductIdRequest, object userState) {
            if ((this.StopSellingProductByProductIdOperationCompleted == null)) {
                this.StopSellingProductByProductIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStopSellingProductByProductIdOperationCompleted);
            }
            this.InvokeAsync("StopSellingProductByProductId", new object[] {
                        StopSellingProductByProductIdRequest}, this.StopSellingProductByProductIdOperationCompleted, userState);
        }
        
        private void OnStopSellingProductByProductIdOperationCompleted(object arg) {
            if ((this.StopSellingProductByProductIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StopSellingProductByProductIdCompleted(this, new StopSellingProductByProductIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("StopSellingProductBySellerCodeResponse", Namespace="http://www.n11.com/ws/schemas")]
        public StopSellingProductBySellerCodeResponse StopSellingProductBySellerCode([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.n11.com/ws/schemas")] StopSellingProductBySellerCodeRequest StopSellingProductBySellerCodeRequest) {
            object[] results = this.Invoke("StopSellingProductBySellerCode", new object[] {
                        StopSellingProductBySellerCodeRequest});
            return ((StopSellingProductBySellerCodeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void StopSellingProductBySellerCodeAsync(StopSellingProductBySellerCodeRequest StopSellingProductBySellerCodeRequest) {
            this.StopSellingProductBySellerCodeAsync(StopSellingProductBySellerCodeRequest, null);
        }
        
        /// <remarks/>
        public void StopSellingProductBySellerCodeAsync(StopSellingProductBySellerCodeRequest StopSellingProductBySellerCodeRequest, object userState) {
            if ((this.StopSellingProductBySellerCodeOperationCompleted == null)) {
                this.StopSellingProductBySellerCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStopSellingProductBySellerCodeOperationCompleted);
            }
            this.InvokeAsync("StopSellingProductBySellerCode", new object[] {
                        StopSellingProductBySellerCodeRequest}, this.StopSellingProductBySellerCodeOperationCompleted, userState);
        }
        
        private void OnStopSellingProductBySellerCodeOperationCompleted(object arg) {
            if ((this.StopSellingProductBySellerCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StopSellingProductBySellerCodeCompleted(this, new StopSellingProductBySellerCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("StartSellingProductByProductIdResponse", Namespace="http://www.n11.com/ws/schemas")]
        public StartSellingProductByProductIdResponse StartSellingProductByProductId([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.n11.com/ws/schemas")] StartSellingProductByProductIdRequest StartSellingProductByProductIdRequest) {
            object[] results = this.Invoke("StartSellingProductByProductId", new object[] {
                        StartSellingProductByProductIdRequest});
            return ((StartSellingProductByProductIdResponse)(results[0]));
        }
        
        /// <remarks/>
        public void StartSellingProductByProductIdAsync(StartSellingProductByProductIdRequest StartSellingProductByProductIdRequest) {
            this.StartSellingProductByProductIdAsync(StartSellingProductByProductIdRequest, null);
        }
        
        /// <remarks/>
        public void StartSellingProductByProductIdAsync(StartSellingProductByProductIdRequest StartSellingProductByProductIdRequest, object userState) {
            if ((this.StartSellingProductByProductIdOperationCompleted == null)) {
                this.StartSellingProductByProductIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartSellingProductByProductIdOperationCompleted);
            }
            this.InvokeAsync("StartSellingProductByProductId", new object[] {
                        StartSellingProductByProductIdRequest}, this.StartSellingProductByProductIdOperationCompleted, userState);
        }
        
        private void OnStartSellingProductByProductIdOperationCompleted(object arg) {
            if ((this.StartSellingProductByProductIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartSellingProductByProductIdCompleted(this, new StartSellingProductByProductIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("StartSellingProductBySellerCodeResponse", Namespace="http://www.n11.com/ws/schemas")]
        public StartSellingProductBySellerCodeResponse StartSellingProductBySellerCode([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.n11.com/ws/schemas")] StartSellingProductBySellerCodeRequest StartSellingProductBySellerCodeRequest) {
            object[] results = this.Invoke("StartSellingProductBySellerCode", new object[] {
                        StartSellingProductBySellerCodeRequest});
            return ((StartSellingProductBySellerCodeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void StartSellingProductBySellerCodeAsync(StartSellingProductBySellerCodeRequest StartSellingProductBySellerCodeRequest) {
            this.StartSellingProductBySellerCodeAsync(StartSellingProductBySellerCodeRequest, null);
        }
        
        /// <remarks/>
        public void StartSellingProductBySellerCodeAsync(StartSellingProductBySellerCodeRequest StartSellingProductBySellerCodeRequest, object userState) {
            if ((this.StartSellingProductBySellerCodeOperationCompleted == null)) {
                this.StartSellingProductBySellerCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartSellingProductBySellerCodeOperationCompleted);
            }
            this.InvokeAsync("StartSellingProductBySellerCode", new object[] {
                        StartSellingProductBySellerCodeRequest}, this.StartSellingProductBySellerCodeOperationCompleted, userState);
        }
        
        private void OnStartSellingProductBySellerCodeOperationCompleted(object arg) {
            if ((this.StartSellingProductBySellerCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartSellingProductBySellerCodeCompleted(this, new StartSellingProductBySellerCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class StopSellingProductByProductIdRequest {
        
        private Authentication authField;
        
        private long productIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class Authentication {
        
        private string appKeyField;
        
        private string appSecretField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appSecret {
            get {
                return this.appSecretField;
            }
            set {
                this.appSecretField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductAttribute {
        
        private long idField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductSkuBasic))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductSku))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductSkuBasicRequest {
        
        private string sellerStockCodeField;
        
        private decimal optionPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sellerStockCode {
            get {
                return this.sellerStockCodeField;
            }
            set {
                this.sellerStockCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal optionPrice {
            get {
                return this.optionPriceField;
            }
            set {
                this.optionPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductSku))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductSkuBasic : ProductSkuBasicRequest {
        
        private decimal currencyAmountField;
        
        private decimal displayPriceField;
        
        private decimal oldOptionPriceField;
        
        private string gtinField;
        
        private long n11CatalogIdField;
        
        private string mpnField;
        
        private string oemField;
        
        private bool bundleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal currencyAmount {
            get {
                return this.currencyAmountField;
            }
            set {
                this.currencyAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal displayPrice {
            get {
                return this.displayPriceField;
            }
            set {
                this.displayPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal oldOptionPrice {
            get {
                return this.oldOptionPriceField;
            }
            set {
                this.oldOptionPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gtin {
            get {
                return this.gtinField;
            }
            set {
                this.gtinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long n11CatalogId {
            get {
                return this.n11CatalogIdField;
            }
            set {
                this.n11CatalogIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mpn {
            get {
                return this.mpnField;
            }
            set {
                this.mpnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string oem {
            get {
                return this.oemField;
            }
            set {
                this.oemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bundle {
            get {
                return this.bundleField;
            }
            set {
                this.bundleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductSku : ProductSkuBasic {
        
        private long idField;
        
        private long versionField;
        
        private string quantityField;
        
        private ProductAttribute[] attributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ProductAttribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductSkuList {
        
        private long idField;
        
        private ProductSku[] stockItemField;
        
        private string productSellerCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProductSku[] stockItem {
            get {
                return this.stockItemField;
            }
            set {
                this.stockItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productSellerCode {
            get {
                return this.productSellerCodeField;
            }
            set {
                this.productSellerCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductBasic {
        
        private long idField;
        
        private string productSellerCodeField;
        
        private string titleField;
        
        private string subtitleField;
        
        private decimal priceField;
        
        private decimal displayPriceField;
        
        private bool isDomesticField;
        
        private string saleStatusField;
        
        private string approvalStatusField;
        
        private ProductSkuList stockItemsField;
        
        private decimal oldPriceField;
        
        private decimal currencyAmountField;
        
        private string currencyTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productSellerCode {
            get {
                return this.productSellerCodeField;
            }
            set {
                this.productSellerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subtitle {
            get {
                return this.subtitleField;
            }
            set {
                this.subtitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal displayPrice {
            get {
                return this.displayPriceField;
            }
            set {
                this.displayPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isDomestic {
            get {
                return this.isDomesticField;
            }
            set {
                this.isDomesticField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string saleStatus {
            get {
                return this.saleStatusField;
            }
            set {
                this.saleStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", IsNullable=true)]
        public string approvalStatus {
            get {
                return this.approvalStatusField;
            }
            set {
                this.approvalStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProductSkuList stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal oldPrice {
            get {
                return this.oldPriceField;
            }
            set {
                this.oldPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal currencyAmount {
            get {
                return this.currencyAmountField;
            }
            set {
                this.currencyAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string currencyType {
            get {
                return this.currencyTypeField;
            }
            set {
                this.currencyTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ResultInfo {
        
        private string statusField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string errorCategoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errorCategory {
            get {
                return this.errorCategoryField;
            }
            set {
                this.errorCategoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class StopSellingProductByProductIdResponse {
        
        private ResultInfo resultField;
        
        private ProductBasic productField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProductBasic product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class StopSellingProductBySellerCodeRequest {
        
        private Authentication authField;
        
        private string productSellerCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productSellerCode {
            get {
                return this.productSellerCodeField;
            }
            set {
                this.productSellerCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class StopSellingProductBySellerCodeResponse {
        
        private ResultInfo resultField;
        
        private ProductBasic productField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProductBasic product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class StartSellingProductByProductIdRequest {
        
        private Authentication authField;
        
        private long productIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class StartSellingProductByProductIdResponse {
        
        private ResultInfo resultField;
        
        private ProductBasic productField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProductBasic product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class StartSellingProductBySellerCodeRequest {
        
        private Authentication authField;
        
        private string productSellerCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productSellerCode {
            get {
                return this.productSellerCodeField;
            }
            set {
                this.productSellerCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class StartSellingProductBySellerCodeResponse {
        
        private ResultInfo resultField;
        
        private ProductBasic productField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProductBasic product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void StopSellingProductByProductIdCompletedEventHandler(object sender, StopSellingProductByProductIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StopSellingProductByProductIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StopSellingProductByProductIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StopSellingProductByProductIdResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StopSellingProductByProductIdResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void StopSellingProductBySellerCodeCompletedEventHandler(object sender, StopSellingProductBySellerCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StopSellingProductBySellerCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StopSellingProductBySellerCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StopSellingProductBySellerCodeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StopSellingProductBySellerCodeResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void StartSellingProductByProductIdCompletedEventHandler(object sender, StartSellingProductByProductIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartSellingProductByProductIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartSellingProductByProductIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StartSellingProductByProductIdResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StartSellingProductByProductIdResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void StartSellingProductBySellerCodeCompletedEventHandler(object sender, StartSellingProductBySellerCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartSellingProductBySellerCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartSellingProductBySellerCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StartSellingProductBySellerCodeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StartSellingProductBySellerCodeResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591